<?php

/**
 * @file
 * Description of module file
 */

define('DESKMP_SITE_KEY', 'mynd5');
define('DESKMP_MULTIPASS_API_KEY', 'e03036f043f6012fb23c12313e001e42');


/**
 * Implementation of hook_menu
 */
function deskmp_menu() {
  $items = array();

  $items['support'] = array(
    'title' => 'Support', 
    'description' => 'Support', 
    'page callback' => 'deskmp_redirect',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}



/**
 * Some explanation of what the function does
 *
 * @param $data
 *   Information about this parameter
 *
 * @return
 *   Return value
 */
function deskmp_redirect() {
  if (user_is_logged_in()) {
    $destination = deskmp_multipass_url();
  }
  
  else {
    $subdomain = DESKMP_SITE_KEY;
    $destination = "http://$subdomain.desk.com";
  }
  
  drupal_goto($destination);
}



/**
 * Some explanation of what the function does
 *
 * @param $data
 *   Information about this parameter
 *
 * @return
 *   Return value
 */
function deskmp_multipass_url() {

  global $user;

  $hash = hash('sha1', DESKMP_MULTIPASS_API_KEY . DESKMP_SITE_KEY, TRUE);
  $salted = substr($hash, 0, 16);
  $iv = 'OpenSSL for Ruby';
  
  // Build json data
  $user_data = array(
    'uid' => $user->uid,
    'customer_email' => $user->mail,
    'customer_name' => $user->name,
    'expires' => date('c', strtotime('+5 minutes')),
  );
  
  $data = json_encode($user_data);
  
  // XOR first block of data with IV
  for ($i = 0; $i < 16; $i++) {
    $data[$i] = $data[$i] ^ $iv[$i];
  }
  
  // pad using standard PKCS#5 padding with block size of 16 bytes
  $pad = 16 - (strlen($data) % 16);
  $data = $data . str_repeat(chr($pad), $pad);
  
  // encrypt data using AES128-cbc
  $cipher = mcrypt_module_open(MCRYPT_RIJNDAEL_128, '', MCRYPT_MODE_CBC, '');
  mcrypt_generic_init($cipher, $salted, $iv);
  $multipass = mcrypt_generic($cipher, $data);
  mcrypt_generic_deinit($cipher);
  
  // Base64 encode the encrypted data
  $multipass = base64_encode($multipass);
  
  // Convert encoded data to the URL safe variant
  $multipass = preg_replace('/\=$/', '', $multipass);
  $multipass = preg_replace('/\n/', '', $multipass);
  $multipass = preg_replace('/\+/', '-', $multipass);
  $multipass = preg_replace('/\//', '_', $multipass);
  
  // Build an HMAC-SHA1 signature using the multipass string and your API key
  $signature = hash_hmac("sha1", $multipass, DESKMP_MULTIPASS_API_KEY, TRUE);
  
  // Base64 encode the signature
  $signature = base64_encode($signature);
  
  // Finally, URL encode the multipass and signature
  $multipass = urlencode($multipass);
  $signature = urlencode($signature);
  
  $subdomain = DESKMP_SITE_KEY;
  return "http://$subdomain.desk.com/customer/authentication/multipass/callback?multipass=$multipass&signature=$signature";
}



function deskmp_request() {
  $url = "https://$api:$secret@$subdomain.mynd5.com/api/$version/$resource.$format";

  $options = array(
    'method' => 'POST',
    'headers' => array('Content-type' => 'application/x-www-form-urlencoded'),
  );
  
  $options['data'] = 'myvariable1=myvalue&myvariable2=myvalue2';
  
  $result = drupal_http_request($url, $options)->data;
}